title: rickylee
description: Game dev & indie projects
url: "https://rickyleecarpenter.github.io"

author:
  name: Ricky-lee Carpenter
  github: RickyleeCarpenter
  linkedin: ricky-lee-carpenter-08a89811a
